### ISSUE TITLE
Feature 1: User can create a nurse entry

### ISSUE THREAD

**Issue by NCFern** [NCFern/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create entries for a nurse.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that allows user to upload a picture and fill out a form containing nurse details.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![1](https://user-images.githubusercontent.com/99868725/190527899-f4dbfec5-2108-44e2-b189-ff1e79a8bc0a.png)
![2](https://user-images.githubusercontent.com/99868725/190527901-69e086b3-6025-4ed2-8aa5-2be0e5198c0d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create and store the entry info

### ☁️ Server Tasks

- [x] Update `server/index.js` to use post method to store user's code into database table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to hold a form 
- [x] Have that form have all of its fields required
- [x] Listen for 'input' events on the photoUrl input to update the src attribute of the photo preview when the input value changes
- [x] Listen for 'submit' events on nurse entry form and:
    - [x] Put the form's input values into a new object to be stored in database
    - [x] Add the nextEntryId to the object
    - [x] Increment the nextEntryId on the data model
    - [x] Prepend the new object to the entries in the data model
    - [x] Reset the form inputs and images preview's src attribute
- [x] Verify that the new entries are saved to local storage and database on page reload
- [x] Verify that each new entry receives an incrementing entryId
- [x] Make sure all input values are validated
- [x] Store code into database

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
