### ISSUE TITLE
Feature 2: User can view the nurse's entry

### ISSUE THREAD

**Issue by NCFern** [NCFern/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a nurse's entry.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Display the user-inputted nurse entry in reverse chronological order so they see the newest one first.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-15 at 5 24 57 PM](https://user-images.githubusercontent.com/99868725/190531042-af9e37b9-c15a-4f9f-afc6-d02b037e0974.png)
![Screen Shot 2022-09-15 at 5 25 40 PM](https://user-images.githubusercontent.com/99868725/190531092-02c1e70b-d83d-4aca-b7f4-d36d6052ad2f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ... (no need atm)
- [ ] Update `data.sql` to ... (no need atm)

### ☁️ Server Tasks

- [ ] Update `server/index.js` to use GET method to pull data from the database
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a page for user to view nurse entry
- [ ] After user submits a nurse entry, the app will display the list of nurses
- [ ] When user clicks the + button on the top, the app will direct the user to an empty nurse entry form
- [ ] When user clicks the 'Nurses Log' area on the top, the app will direct the user to the list of nurses
- [ ] When there are no nurse entires, display a 'no nurse entries' message
- [ ] Set view nurse entries as landing page for the app

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
